theme: jekyll-theme-architect
title: Py Docstrings To Markdown
description: A browser-based tool that extracts and formats Python docstrings into Markdown from .py and .llsp3 (LEGO SPIKE) files. Preferred is Google-style docstrings.